---
title: 'ANOVA'
subtitle: 'simulations'
author: 'dacarras'
date: '`r format(Sys.time(), "%a %b %d, %Y")`'
output:
  html_document:
    theme: paper
    highlight: kate
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    fig_width: 10 
    fig_height: 8 
---

<style>
  .main-container {
    max-width: 1600px !important;
  }
  .list-group-item.active, 
  .list-group-item.active:focus, 
  .list-group-item.active:hover {
    background-color: #373334;
  }
</style>


# Simulations

## ANOVA null difference

```{r, echo=TRUE}

#------------------------------------------------------------------------------
# comparing simulation
#------------------------------------------------------------------------------

#------------------------------------------------
# null separation simulation
#------------------------------------------------

#--------------------------------------
# define parameters
#--------------------------------------

beta <- .05

#--------------------------------------
# simulation
#--------------------------------------

set.seed(321)
library(dplyr)
library(simglm)

sim_arguments <- list(
  formula = y ~ 1 + group,
  fixed = list(
               group = list(var_type = 'factor', levels = c('group_1', 'group_2','group_3'))),
  error = list(variance = 10),
  sample_size = 90,
  reg_weights = c(50,beta,-beta)
)

#--------------------------------------
# generate data
#--------------------------------------

simulated_data <- simulate_fixed(data = NULL, sim_arguments) %>%
simulate_error(sim_arguments) %>%
generate_response(sim_arguments) %>%
dplyr::select(y, group_1, group_2, group)

#--------------------------------------
# create plot
#--------------------------------------

library(tidyverse)
library(ggplot2)
library(ggridges)
library(scales)

ggplot(simulated_data, aes(x = y, y = group, fill = group, height = ..density..)) +
  geom_density_ridges(rel_min_height = 0.005) +
  scale_fill_manual(values = c("black", "grey30",'grey50'), guide = FALSE) + 
  theme_minimal() +
  theme(
    panel.grid.minor = element_blank()
    )

#--------------------------------------
# anova result
#--------------------------------------

aov(y ~ 1 + as.factor(group), data = simulated_data) %>%
summary()

#--------------------------------------
# regression results
#--------------------------------------

lm(y ~ 1 + as.factor(group), data = simulated_data) %>%
broom::glance()

```

## ANOVA separated by 1

```{r, echo=TRUE}

#------------------------------------------------------------------------------
# comparing simulation
#------------------------------------------------------------------------------

#------------------------------------------------
# separated by 1
#------------------------------------------------

#--------------------------------------
# define parameters
#--------------------------------------

beta <- 1

#--------------------------------------
# simulation
#--------------------------------------

set.seed(321)
library(dplyr)
library(simglm)

sim_arguments <- list(
  formula = y ~ 1 + group,
  fixed = list(
               group = list(var_type = 'factor', levels = c('group_1', 'group_2','group_3'))),
  error = list(variance = 10),
  sample_size = 90,
  reg_weights = c(50,beta,-beta)
)

#--------------------------------------
# generate data
#--------------------------------------

simulated_data <- simulate_fixed(data = NULL, sim_arguments) %>%
simulate_error(sim_arguments) %>%
generate_response(sim_arguments) %>%
dplyr::select(y, group_1, group_2, group)

#--------------------------------------
# create plot
#--------------------------------------

library(tidyverse)
library(ggplot2)
library(ggridges)
library(scales)

ggplot(simulated_data, aes(x = y, y = group, fill = group, height = ..density..)) +
  geom_density_ridges(rel_min_height = 0.005) +
  scale_fill_manual(values = c("black", "grey30",'grey50'), guide = FALSE) + 
  theme_minimal() +
  theme(
    panel.grid.minor = element_blank()
    )

#--------------------------------------
# anova result
#--------------------------------------

aov(y ~ 1 + as.factor(group), data = simulated_data) %>%
summary()

#--------------------------------------
# regression results
#--------------------------------------

lm(y ~ 1 + as.factor(group), data = simulated_data) %>%
broom::glance()

```

## ANOVA separated by 5

```{r, echo=TRUE}

#------------------------------------------------------------------------------
# comparing simulation
#------------------------------------------------------------------------------

#------------------------------------------------
# separated by 5
#------------------------------------------------

#--------------------------------------
# define parameters
#--------------------------------------

beta <- 5

#--------------------------------------
# simulation
#--------------------------------------

set.seed(321)
library(dplyr)
library(simglm)

sim_arguments <- list(
  formula = y ~ 1 + group,
  fixed = list(
               group = list(var_type = 'factor', levels = c('group_1', 'group_2','group_3'))),
  error = list(variance = 10),
  sample_size = 90,
  reg_weights = c(50,beta,-beta)
)

#--------------------------------------
# generate data
#--------------------------------------

simulated_data <- simulate_fixed(data = NULL, sim_arguments) %>%
simulate_error(sim_arguments) %>%
generate_response(sim_arguments) %>%
dplyr::select(y, group_1, group_2, group)

#--------------------------------------
# create plot
#--------------------------------------

library(tidyverse)
library(ggplot2)
library(ggridges)
library(scales)

ggplot(simulated_data, aes(x = y, y = group, fill = group, height = ..density..)) +
  geom_density_ridges(rel_min_height = 0.005) +
  scale_fill_manual(values = c("black", "grey30",'grey50'), guide = FALSE) + 
  theme_minimal() +
  theme(
    panel.grid.minor = element_blank()
    )

#--------------------------------------
# anova result
#--------------------------------------

aov(y ~ 1 + as.factor(group), data = simulated_data) %>%
summary()

#--------------------------------------
# regression results
#--------------------------------------

lm(y ~ 1 + as.factor(group), data = simulated_data) %>%
broom::glance()

```

## ANOVA separated by 10

```{r, echo=TRUE}

#------------------------------------------------------------------------------
# comparing simulation
#------------------------------------------------------------------------------

#------------------------------------------------
# separated by 10
#------------------------------------------------

#--------------------------------------
# define parameters
#--------------------------------------

beta <- 10

#--------------------------------------
# simulation
#--------------------------------------

set.seed(321)
library(dplyr)
library(simglm)

sim_arguments <- list(
  formula = y ~ 1 + group,
  fixed = list(
               group = list(var_type = 'factor', levels = c('group_1', 'group_2','group_3'))),
  error = list(variance = 10),
  sample_size = 90,
  reg_weights = c(50,beta,-beta)
)

#--------------------------------------
# generate data
#--------------------------------------

simulated_data <- simulate_fixed(data = NULL, sim_arguments) %>%
simulate_error(sim_arguments) %>%
generate_response(sim_arguments) %>%
dplyr::select(y, group_1, group_2, group)

#--------------------------------------
# create plot
#--------------------------------------

library(tidyverse)
library(ggplot2)
library(ggridges)
library(scales)

ggplot(simulated_data, aes(x = y, y = group, fill = group, height = ..density..)) +
  geom_density_ridges(rel_min_height = 0.005) +
  scale_fill_manual(values = c("black", "grey30",'grey50'), guide = FALSE) + 
  theme_minimal() +
  theme(
    panel.grid.minor = element_blank()
    )

#--------------------------------------
# anova result
#--------------------------------------

aov(y ~ 1 + as.factor(group), data = simulated_data) %>%
summary()

#--------------------------------------
# regression results
#--------------------------------------

lm(y ~ 1 + as.factor(group), data = simulated_data) %>%
broom::glance()

```

## ANOVA separated by 20

```{r, echo=TRUE}

#------------------------------------------------------------------------------
# comparing simulation
#------------------------------------------------------------------------------

#------------------------------------------------
# separated by 20
#------------------------------------------------

#--------------------------------------
# define parameters
#--------------------------------------

beta <- 20

#--------------------------------------
# simulation
#--------------------------------------

set.seed(321)
library(dplyr)
library(simglm)

sim_arguments <- list(
  formula = y ~ 1 + group,
  fixed = list(
               group = list(var_type = 'factor', levels = c('group_1', 'group_2','group_3'))),
  error = list(variance = 10),
  sample_size = 90,
  reg_weights = c(50,beta,-beta)
)

#--------------------------------------
# generate data
#--------------------------------------

simulated_data <- simulate_fixed(data = NULL, sim_arguments) %>%
simulate_error(sim_arguments) %>%
generate_response(sim_arguments) %>%
dplyr::select(y, group_1, group_2, group)

#--------------------------------------
# create plot
#--------------------------------------

library(tidyverse)
library(ggplot2)
library(ggridges)
library(scales)

ggplot(simulated_data, aes(x = y, y = group, fill = group, height = ..density..)) +
  geom_density_ridges(rel_min_height = 0.005) +
  scale_fill_manual(values = c("black", "grey30",'grey50'), guide = FALSE) + 
  theme_minimal() +
  theme(
    panel.grid.minor = element_blank()
    )

#--------------------------------------
# anova result
#--------------------------------------

aov(y ~ 1 + as.factor(group), data = simulated_data) %>%
summary()

#--------------------------------------
# regression results
#--------------------------------------

lm(y ~ 1 + as.factor(group), data = simulated_data) %>%
broom::glance()

```
