---
title: "Medidas repetidas"
subtitle: "PSI4035 Taller 11"
author: "dacarras"
output:
  html_document:
    theme: paper
    highlight: kate
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    fig_width: 10 
    fig_height: 10 
---

<style>
  .main-container {
    max-width: 1600px !important;
  }
  .list-group-item.active,  
  .list-group-item.active:focus, 
  .list-group-item.active:hover {
    background-color: #373334;
  }
</style>


```{r setup, include=FALSE}
#--------------------------------------
# setup
#--------------------------------------

# knitr option
knitr::opts_chunk$set(dev = 'png')
options(knitr.kable.NA = '')
options(digits = 7)
options(scipen = 999999)

# remove all previous objects
rm(list = ls())

# fonts
Sys.setenv(LANG="en_US.UTF-8")


```

# Taller 11: Medidas repetidas

## Cargar datos

```{r , echo=TRUE, warning=FALSE}

#----------------------------------------------------------
# cargar datos
#----------------------------------------------------------

#--------------------------------------
# cargar dplyr
#--------------------------------------

library(dplyr)

#--------------------------------------
# datos Vik (2014, p234)
#--------------------------------------

table_19_2 <- read.table(text = "
subject   t1     t2       t3
1          3      5        6
2          5      4        3
3          6      4        3
4          8      5        6
5          9     10       11
6         11      8        7
7         19     14       13
8         15     15       16
9         16     16       17
10        16      7        6
11        19      8        7
12        17      9       10
13         3      3        2
14         5      5        6
15         4      6        7
16         6      8        7
17         8      9        8
18        10     11       12
19        24     19       20
20        24     20       19
21        22     21       20
22        23     10       11
23        19     11       12
24        20     12       11
", header = TRUE, stringsAsFactors = FALSE)


#--------------------------------------
# mostrar datos
#--------------------------------------

knitr::kable(table_19_2, digits = 3)

#--------------------------------------
# datos Vik (2014, p234) in long format
#--------------------------------------

person_period <- read.table(text = "
subject    wave  score
      1    t1        3
      1    t2        5
      1    t3        6
      2    t1        5
      2    t2        4
      2    t3        3
      3    t1        6
      3    t2        4
      3    t3        3
      4    t1        8
      4    t2        5
      4    t3        6
      5    t1        9
      5    t2       10
      5    t3       11
      6    t1       11
      6    t2        8
      6    t3        7
      7    t1       19
      7    t2       14
      7    t3       13
      8    t1       15
      8    t2       15
      8    t3       16
      9    t1       16
      9    t2       16
      9    t3       17
     10    t1       16
     10    t2        7
     10    t3        6
     11    t1       19
     11    t2        8
     11    t3        7
     12    t1       17
     12    t2        9
     12    t3       10
     13    t1        3
     13    t2        3
     13    t3        2
     14    t1        5
     14    t2        5
     14    t3        6
     15    t1        4
     15    t2        6
     15    t3        7
     16    t1        6
     16    t2        8
     16    t3        7
     17    t1        8
     17    t2        9
     17    t3        8
     18    t1       10
     18    t2       11
     18    t3       12
     19    t1       24
     19    t2       19
     19    t3       20
     20    t1       24
     20    t2       20
     20    t3       19
     21    t1       22
     21    t2       21
     21    t3       20
     22    t1       23
     22    t2       10
     22    t3       11
     23    t1       19
     23    t2       11
     23    t3       12
     24    t1       20
     24    t2       12
     24    t3       11
", header = TRUE, stringsAsFactors = FALSE)


#--------------------------------------
# mostrar datos
#--------------------------------------

knitr::kable(person_period, digits = 3)


```


## Preparar datos

### From wide data to long data

```{r , echo=TRUE, warning=FALSE}

# -----------------------------------------------
# preparar datos
# -----------------------------------------------

#--------------------------------------
# data in wide
#--------------------------------------

person_level <- table_19_2

#--------------------------------------
# display data in wide
#--------------------------------------

knitr::kable(person_level, digits = 3)

#--------------------------------------
# data in long
#--------------------------------------

library(dplyr)
library(tidyr)

data_long <- person_level %>%
             tidyr::pivot_longer(
              data = ., 
              cols = !subject, 
              names_to  = "wave", 
              values_to = "score"
              ) %>%
             mutate(time = case_when(
              wave == 't1' ~ 0,
              wave == 't2' ~ 1,
              wave == 't3' ~ 2
              )) %>%
             mutate(time_q = time^2)

#--------------------------------------
# display data in wide
#--------------------------------------

knitr::kable(data_long, digits = 3)

```

### From long to wide

```{r , echo=TRUE, warning=FALSE}

# -----------------------------------------------
# preparar datos
# -----------------------------------------------

#--------------------------------------
# data in wide
#--------------------------------------

data_stacked <- person_period

#--------------------------------------
# display data in wide
#--------------------------------------

knitr::kable(data_stacked, digits = 3)

#--------------------------------------
# data in long
#--------------------------------------

library(dplyr)
library(tidyr)

data_wide <- data_stacked %>%
             tidyr::pivot_wider(
              data = ., 
              id_cols = subject, 
              names_from  = "wave", 
              values_from   = "score"
              )

#--------------------------------------
# display data in wide
#--------------------------------------

knitr::kable(data_wide, digits = 3)

```

# Modelling

## Paired t-test

```{r , echo=TRUE, warning=FALSE}

# -----------------------------------------------
# preparar datos
# -----------------------------------------------

#--------------------------------------
# data in long
#--------------------------------------

# t_test asumiendo varianzas equivalentes (homocedasticidad de varianzas)
data_long %>%
dplyr::filter(wave %in% c('t1','t2')) %>%
t.test(formula = score ~ wave,
       data = .,
       alternative = c("two.sided"),
       paired = TRUE, 
       var.equal = TRUE,
       conf.level = 0.95)

#--------------------------------------
# data in wide
#--------------------------------------

# t_test asumiendo varianzas equivalentes (homocedasticidad de varianzas)
t.test(x = data_wide$t1,
       y = data_wide$t2,
       alternative = c("two.sided"),
       paired = TRUE, 
       var.equal = TRUE,
       conf.level = 0.95)

```

## ANOVA medidas repetidas (two times)

```{r , echo=TRUE, warning=FALSE}

# -----------------------------------------------
# anova with data long format
# -----------------------------------------------

#--------------------------------------
# replicate Vik F satistic
#--------------------------------------

data_long %>%
dplyr::filter(wave %in% c('t1','t2')) %>%
rstatix::anova_test(
  data   = .,
  dv     = score,
  wid    = subject,
  within = wave
  ) %>%
rstatix::get_anova_table() 


```

## Fixed effects

```{r , echo=TRUE, warning=FALSE}

# -----------------------------------------------
# regression
# -----------------------------------------------

#--------------------------------------
# removing between variance
#--------------------------------------

model_1 <- lm(score ~ time + time_q + as.factor(subject), data = data_long)
summary(model_1)


```

## Random effects

```{r , echo=TRUE, warning=FALSE}

# -----------------------------------------------
# multilevel model
# -----------------------------------------------

#--------------------------------------
# modelling between variance
#--------------------------------------

model_2 <- lme4::lmer(score ~ time + time_q + (1|subject), data = data_long, REML = FALSE)
summary(model_2)

#--------------------------------------
# intra class correlation
#--------------------------------------

r4sda::get_icc(model_2)

# -----------------------------------------------
# random effect visualization
# -----------------------------------------------

r4sda::caterpillar_plot(model_2)

```


## Latent Growth

```{r , echo=TRUE, warning=FALSE}

# -----------------------------------------------
# multilevel model
# -----------------------------------------------

#--------------------------------------
# specify model
#--------------------------------------

code_3 <- '
i =~ 1*t1
i =~ 1*t2
i =~ 1*t3

s =~  0*t1
s =~  1*t2
s =~  2*t3

q =~ 0*t1
q =~ 1*t2
q =~ 4*t3

s~~0*q
s~~0*s
q~~0*q

t1~~(a)*t1
t2~~(a)*t2
t3~~(a)*t3

'

#--------------------------------------
# fit model
#--------------------------------------

model_3 <- lavaan::sem(code_3, data = data_wide, mimic="Mplus", estimator = "MLR")
summary(model_3)


```


