---
title: "ANCOVA"
subtitle: "PSI4035 Taller 10"
author: "dacarras"
output:
  html_document:
    theme: paper
    highlight: kate
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    fig_width: 10 
    fig_height: 10 
---

<style>
  .main-container {
    max-width: 1600px !important;
  }
  .list-group-item.active,  
  .list-group-item.active:focus, 
  .list-group-item.active:hover {
    background-color: #373334;
  }
</style>


```{r setup, include=FALSE}
#--------------------------------------
# setup
#--------------------------------------

# knitr option
knitr::opts_chunk$set(dev = 'png')
options(knitr.kable.NA = '')
options(digits = 7)
options(scipen = 999999)

# remove all previous objects
rm(list = ls())

# fonts
Sys.setenv(LANG="en_US.UTF-8")


```

# Taller 10: ANCOVA

## Cargar datos

```{r , echo=TRUE, warning=FALSE}

#----------------------------------------------------------
# cargar datos
#----------------------------------------------------------

#--------------------------------------
# cargar dplyr
#--------------------------------------

library(dplyr)

#--------------------------------------
# datos Vik (2014, p212)
#--------------------------------------

table_17_2 <- read.table(text = "
subject   score      age      sex
1         3          21       m
2         5          22       m
3         6          22       m
4         8          22       m
5         9          21       m
6         11         19       m
7         19         20       m
8         15         19       m
9         16         18       m
10        16         17       m
11        19         21       m
12        17         22       m
13        3          23       f
14        5          24       f
15        4          25       f
16        6          23       f
17        8          22       f
18        10         21       f
19        24         18       f
20        24         18       f
21        22         19       f
22        23         20       f
23        19         20       f
24        20         21       f
", header = TRUE, stringsAsFactors = FALSE)

# Nota: sex (men = m, woman = f)

#--------------------------------------
# mostrar datos
#--------------------------------------

knitr::kable(table_17_2, digits = 3)

```


## Preparar datos

```{r , echo=TRUE, warning=FALSE}


# -----------------------------------------------
# preparar datos
# -----------------------------------------------

c_mean <- function (x, j) {
    ave(x, j, FUN = function(x) mean(x, na.rm = T))
}


#--------------------------------------
# computes
#--------------------------------------

data_model <- table_17_2 %>%
              mutate(id_k = 1) %>%
              mutate(age_m = age - c_mean(age, id_k)) %>%  # centering to the grand mean
              mutate(sex_f = as.factor(sex)) %>%
              mutate(male_d = case_when(
                sex == 'm' ~   1,
                sex == 'f' ~  -1
              )) %>%
              mutate(female_d = case_when(
                sex == 'm' ~   -1,
                sex == 'f' ~    1
              )) %>%
              mutate(male = case_when(
                sex == 'm' ~  1,
                sex == 'f' ~  0
              )) %>%
              mutate(female = case_when(
                sex == 'm' ~  0,
                sex == 'f' ~  1
              )) %>%
              mutate(pseudo = score - -2.56*age_m) %>%
              dplyr::glimpse()

```

## Ajustar Modelos

```{r , echo=TRUE, warning=FALSE}

#----------------------------------------------------------
# modelos
#----------------------------------------------------------

#--------------------------------------
# ajustar modelos
#--------------------------------------


f00 <- as.formula(score  ~ + 1)
f01 <- as.formula(score  ~ + 1 + male_d)
f02 <- as.formula(score  ~ + 1 + age_m)
f03 <- as.formula(score  ~ + 1 + age_m + male_d)
f04 <- as.formula(pseudo ~ + 1 + male_d)
f05 <- as.formula(score  ~ + 1 + age_m)
f06 <- as.formula(score  ~ + 1 + age_m + female_d)
f07 <- as.formula(score  ~ + 1 + age_m)
f08 <- as.formula(score  ~ + 1 + age_m + male)
f09 <- as.formula(score  ~ + 1 + age_m)
f10 <- as.formula(score  ~ + 1 + age_m + female)

#--------------------------------------
# ajustar modelos
#--------------------------------------

m00 <- lm(f00, data = data_model)
m01 <- lm(f01, data = data_model)
m02 <- lm(f02, data = data_model)
m03 <- lm(f03, data = data_model)
m04 <- lm(f04, data = data_model)
m05 <- lm(f05, data = data_model)
m06 <- lm(f06, data = data_model)
m07 <- lm(f07, data = data_model)
m08 <- lm(f08, data = data_model)
m09 <- lm(f09, data = data_model)
m10 <- lm(f10, data = data_model)

#--------------------------------------
# tabla de modelos
#--------------------------------------

texreg::screenreg(
    list(m01, m02, m03, m04, m05, m06, m07, m08, m09, m10),
    star.symbol = "*", 
    center = TRUE, 
    doctype = FALSE,
    dcolumn = TRUE, 
    booktabs = TRUE,
    single.row = FALSE
    )


```

## Tabla F

```{r , echo=TRUE, warning=FALSE}

#----------------------------------------------------------
# modelos
#----------------------------------------------------------

#--------------------------------------
# F table for 17.4
#--------------------------------------

anova(m03)

#--------------------------------------
# model comparison
#--------------------------------------

anova(m02, m03) 

```

## ANOVA y sumas de cuadrados

```{r , echo=TRUE, warning=FALSE}

#----------------------------------------------------------
# modelos
#----------------------------------------------------------

#--------------------------------------
# Tukey
#--------------------------------------

#--------------------------------------
# misc
#--------------------------------------

rstatix::anova_test(score ~ age_m + male_d, data = data_model)

#------------------------------------------------------------------------------
# errores cuadrados
#------------------------------------------------------------------------------

#----------------------------------------------------------
# función SSE
#----------------------------------------------------------

sse_model <- function(model){

y     <- model$model[,1]
y_hat <- model$fitted.values
squared_errors <- (y - y_hat)^2
sse <- sum(squared_errors)

return(sse)
}

#----------------------------------------------------------
# extraer SSE
#----------------------------------------------------------

sse_00 <- sse_model(m00)
sse_02 <- sse_model(m02)
sse_03 <- sse_model(m03)

#----------------------------------------------------------
# crear tabla
#----------------------------------------------------------

sse_table <- data.frame(
  model = c(
    'null model', 
    'augmented model', 
    'with covariate'
    ),
  see = c(sse_00, sse_02, sse_03)
  )

#----------------------------------------------------------
# mostrar tabla
#----------------------------------------------------------

knitr::kable(sse_table, digits = 2)

```

## Post hoc comparisons

```{r , echo=TRUE, warning=FALSE}

#----------------------------------------------------------
# modelos
#----------------------------------------------------------

#--------------------------------------
# Tukey
#--------------------------------------

library(multcomp)
ancova_model <- aov(score ~ age_m + sex_f, data = data_model)
post_hocs <- glht(ancova_model, linfct = mcp(sex_f = "Tukey"))
summary(post_hocs)


#----------------------------------------------------------
# bonferroni
#----------------------------------------------------------

rstatix::emmeans_test(
    score ~ sex_f, 
    covariate = age_m,
    data = data_model,
    p.adjust.method = "bonferroni"
    )


```
