---
title: "dem_16"
subtitle: "data examples"
author: "dacarras"
output: github_document
---


# Descripción

Datos del Estudio Internacional sobre Educación Cívica y Ciudadana
(ICCS). Esta tabla de datos, incluye las observaciones del módulo
internacional, y del modulo latino americano. Estos datos inlcuyen
500 casos de cada país, ademas de variables tales como: sexo,
edad, perfil de concepciones de la democracia, creencias
antidemocraticas, conocimiento cívico, nivel socioeconómico, y
educacion de los padres, y niveles de conocimiento cívico.

# Codebook

|variable|descripción|
|:-- |:-- |
|id_i|id único del caso|
|ctry|nombre del país|
|sex|sexo del estudiante|
|age|edad del estudiante en años|
|dem|perfil de concepciones de las democracia (1 = minimalista, 2 = complejo, 3 = limitado)|
|dem_group|perfil de concepciones de las democracia (en texto)|
|aut|creencias antidemocráticas |
|civ|conocimiento cívico |
|ses|nivel socioecónomico |
|edu|educación de los padres (1 = educación universitaria, 0 = otro nivel educativo)|
|level|niveles de conocimiento cívico (numérico) (3 = alta sofisticación, 2 = medio, 1 = bajo, 0 = muy bajo)|
|level_lab|niveles de conocimiento cívico (Level 3 = alta sofisticación, Level 2 = medio, Level 1 = bajo, Level 0 = muy bajo)|